/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{js,ts,jsx,tsx}"],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "on-surface-variant": "#43493e",
        "secondary-container": "#e1e3e4",
        "on-primary-fixed-variant": "#2d4f1e",
        surface: "#f9f9ff",
        "inverse-surface": "#293040",
        "on-secondary": "#ffffff",
        "on-primary-container": "#98c083",
        "surface-container-lowest": "#ffffff",
        tertiary: "#511e3a",
        "on-primary-fixed": "#062100",
        "surface-container-low": "#f1f3ff",
        "secondary-fixed-dim": "#c5c7c8",
        "on-tertiary": "#ffffff",
        "secondary-fixed": "#e1e3e4",
        "on-tertiary-container": "#e9a0c1",
        "primary-fixed": "#c5efad",
        "error-container": "#ffdad6",
        "surface-container-highest": "#dce2f7",
        "surface-bright": "#f9f9ff",
        "on-surface": "#141b2b",
        "surface-variant": "#dce2f7",
        "on-secondary-fixed-variant": "#454748",
        background: "#f9f9ff",
        "on-primary": "#ffffff",
        "inverse-on-surface": "#edf0ff",
        "primary-fixed-dim": "#a9d293",
        "on-background": "#141b2b",
        secondary: "#5c5f60",
        "tertiary-fixed-dim": "#fcb1d3",
        outline: "#73796d",
        "on-error-container": "#93000a",
        "surface-tint": "#446733",
        "primary-container": "#2d4f1e",
        "on-secondary-fixed": "#191c1d",
        "on-error": "#ffffff",
        "on-tertiary-fixed": "#380824",
        primary: "#173809",
        "surface-dim": "#d3daef",
        "on-tertiary-fixed-variant": "#6c3451",
        "surface-container-high": "#e1e8fd",
        "on-secondary-container": "#626566",
        "tertiary-container": "#6c3451",
        "tertiary-fixed": "#ffd8e7",
        "outline-variant": "#c3c8bb",
        "inverse-primary": "#a9d293",
        "surface-container": "#e9edff",
        error: "#ba1a1a",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        lg: "40px",
        gutter: "20px",
        xl: "64px",
        md: "24px",
        xs: "8px",
        sm: "16px",
        "container-max": "1280px",
        base: "4px",
      },
      fontFamily: {
        "label-md": ["Inter"],
        "headline-lg": ["Inter"],
        "body-sm": ["Inter"],
        "headline-md": ["Inter"],
        "label-caps": ["Inter"],
        "headline-lg-mobile": ["Inter"],
        "body-lg": ["Inter"],
      },
      fontSize: {
        "label-md": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "headline-lg": ["32px", { lineHeight: "40px", letterSpacing: "-0.02em", fontWeight: "600" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-md": ["20px", { lineHeight: "28px", fontWeight: "600" }],
        "label-caps": ["12px", { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "700" }],
        "headline-lg-mobile": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
        "body-lg": ["16px", { lineHeight: "24px", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
};
